In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [67]:
df = pd.read_csv('../../datasets/jigsaw-multilingual-toxic-comment-classification/jigsaw-toxic-comment-train.csv')
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [68]:
train, test = train_test_split(df[['id', 'comment_text', 'toxic']], test_size=0.05)
val, test = train_test_split(test, test_size=0.5)
train.to_csv('train_data.csv', index=False)
val.to_csv('val_data.csv', index=False)
test.to_csv('test_data.csv', index=False)

In [53]:
def count_data(df):
    print('0:', len(df[df['toxic'] == 0]), '1:', len(df[df['toxic'] == 1]))

In [55]:
count_data(train)
count_data(test)
count_data(val)

0: 192069 1: 20302
0: 5049 1: 540
0: 5047 1: 542

In [59]:
def count_data(df):
    print('0:', len(df[df['toxic'] < 0.5]), '1:', len(df[df['toxic'] >= 0.5]))

In [60]:
df2 = pd.read_csv('../../datasets/jigsaw-multilingual-toxic-comment-classification/jigsaw-unintended-bias-train.csv')
df2.head()

,id,comment_text,toxic,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,article_id,rating,funny,wow,sad,likes,disagree,sexual_explicit,identity_annotator_count,toxicity_annotator_count
0,59848,"This is so cool. It's like, 'would you want yo...",0.000000,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
1,59849,Thank you!! This would make my life a lot less...,0.000000,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
2,59852,This is such an urgent design problem; kudos t...,0.000000,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
3,59855,Is this something I'll be able to install on m...,0.000000,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
4,59856,haha you guys are a bunch of losers.,0.893617,0.021277,0.0,0.021277,0.87234,0.0,0.0,0.0,...,2006,rejected,0,0,0,1,0,0.0,4,47

In [62]:
train, test = train_test_split(df2[['id', 'comment_text', 'toxic']], test_size=0.05)
val, test = train_test_split(test, test_size=0.5)
train.to_csv('train_data_unbiased.csv', index=False)
val.to_csv('val_data_unbiased.csv', index=False)
test.to_csv('test_data_unbiased.csv', index=False)

In [64]:
count_data(train)
count_data(test)
count_data(val)

0: 1662562 1: 144522
0: 43674 1: 3881
0: 43847 1: 3708